### ISSUE TITLE
Indentline disappear when open lazy loaded vimfiler or nerdtree on the right.

### ISSUE THREAD

**Issue by wsdjeg** [Yggdroot/indentLine#149]
1. open a vim file,you can see indentline,then type F3 which map to Vimfiler to open vimfiler,the indentline disappear.
2. run IndentLinesDisable and IndentLinesEnable you now can see indentline.
3. then type F3 the Indentline will not disappear,so I think it is due to Vimfiler or nerdtree are lazy loaded,BTW my plugin manager is dein.vim ,wrote by @Shougo

**Comment by Shougo** [comment]
Please update neobundle and dein.vim to the latest version.
And please create minimal .vimrc less than 50 lines and upload the reproduce ways.
We have not ESP skills.

**Comment by Yggdroot** [comment]
This issue is similar with #146.

**Comment by Shougo** [comment]
Hm.  I think nested is needed in the autocmd.
`:help autocmd-nested`.

**Comment by Yggdroot** [comment]
Can not reproduce.

**Comment by wsdjeg** [comment]
closed, this issue has been fixed.

**Comment by wsdjeg** [comment]
sorry, Still huppen, I will create minivimrc for testting.

**Comment by wsdjeg** [comment]
@Shougo @Yggdroot 
I have got it, it is due to the vimfiler change the value of conceallevel to 3. but indentline need it to be 2;
after open vimfiler, `verbose set conceallevel?` show me:
```
conceallevel=3                                                                                                                                       
        Last set from ~/.cache/vimfiles/repos/github.com/Shougo/vimfiler.vim/autoload/vimfiler/init.vim
```

**Comment by Shougo** [comment]
I have fixed the problem.
Please update vimfiler.

**Comment by wsdjeg** [comment]
I am  sorry, in vimfiler, your are using `setl`, so this issue maybe not caused by `setl conceallevel`. after update vimfiler, I still get this issue. it is hard for me to point it out.

**Comment by Shougo** [comment]
@wsdjeg I cannot reproduce the problem.
I have changed `conceallevel` to 2.
You should create minimal init.vim and reproduce ways.  I will test it.

**Comment by wsdjeg** [comment]
@Shougo sorry, I also can not reproduce this problem in minivimrc. only happend in my DotFiles, I wll try to find it out. which plugin cause this issue. thanks all the same.
