### ISSUE TITLE
Error with IndentLinesDisable using new version

### ISSUE THREAD

**Issue by wbthomason** [Yggdroot/indentLine#201]
When `g:indentLine_newVersion = 1`, switching between files yields a large number of "ID not found" errors while running `IndentLinesDisable`. Setting `g:indentLine_newVersion = 0` fixes this behavior. I'm running Arch and Neovim 0.2.0. This bug seems to have been introduced by the [changes to IndentLinesDisable](https://github.com/Yggdroot/indentLine/commit/2ceee22d25961dcc217eadbdffe6a4b043655d13#diff-c1e6b5a05be5fe94918bbdd60691fa89R140) in the latest commit.

**Comment by cpassos** [comment]
I'm also experiencing this, but set `g:indentLine_newVersion = 0` does not fix for me. I'm running Arch and Vim 8.0.

**Comment by wbthomason** [comment]
@cpassos Are you setting the variable in your `.vimrc`, or while in a buffer? If the former, then the workaround isn't working for you because the value gets reset in `after/plugin/indentLine.vim`. It only works for me when I run `:let g:indentLine_newVersion=0` inside of a buffer.

**Comment by cpassos** [comment]
Oh, right, setting in a buffer fixes it for me.

**Comment by Yggdroot** [comment]
How to reproduce it? You don't have to set the variable `g:indentLine_newVersion`, the plugin will auto detect the value of it.

**Comment by wbthomason** [comment]
I'll try to put together a minimal reproducing config, but it's not happening every time I load a file, so it may be hard to reproduce.

The autodetection of `g:indentLine_newVersion` is what I was trying to avoid, as I only see this problem when `g:indentLine_newVersion = 1` (which is what the autodetection sets it to for me).

**Comment by Yggdroot** [comment]
A wrokaround has been commit, now you can set `let g:indentLine_newVersion=0` to avoid the issue.
@wbthomason Need your help to know the steps of reproducing it, thanks.

**Comment by Yggdroot** [comment]
I think there are some plugin that have called `clearmatches()`, you can grep the code in all your plugins to have a try.

**Comment by wbthomason** [comment]
[incsearch.vim](https://github.com/haya14busa/incsearch.vim) and [ALE](https://github.com/w0rp/ale) are the two that match and would've been active when I have seen this bug for me.

I'll have time late tomorrow to try and assemble a minimal reproducing config if this isn't enough info.

**Comment by Yggdroot** [comment]
I find ALE has `clearmatches()` [here](https://github.com/w0rp/ale/blob/master/autoload/ale/highlight.vim#L113), maybe it's the root cause. 
I think vim's plugin should not use `clearmatches()`, because it may clear the matches defined by other plugin.

**Comment by Yggdroot** [comment]
Fixed.

**Comment by wbthomason** [comment]
I can no longer reproduce the issue; I agree with your diagnosis and fix.

**Comment by magicalbanana** [comment]
I still have this issue but only when I use ctags to go to a definition. Not sure about other file types but I am experiencing this in `go`.

**Comment by Yggdroot** [comment]
Are you using the latest version? What is your steps to reproduce it?
