### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by mpfusion** [Yggdroot/indentLine#48]
While I really like your plugin, it makes vim unusably slow.
### How to reproduce

```
wget https://raw.github.com/Yggdroot/indentLine/42cf0572926b9c415d2275e040bdcc60c33f9096/after/plugin/indentLine.vim
vim -N -u NONE -S indentLine.vim \
  -c 'syntax on|help grep|wincmd L|set relativenumber|norm 60G'
```

Then navigate up and down using `j` and `k`.
### Result

Vim maxes out my 2GHz CPU and becomes unusably slow. 
### Expected result

A slight impact on performance but definitely not maxing out the CPU and slowing vim down that much.
### Version
- indentLine: 42cf057292
- vim: 7.4b BETA, Included patches: 1-15

**Comment by Leandros** [comment]
`let g:indentLine_faster = 1` seem to work, but it'll remove the leading spaces, is there a way to bring them back?

**Comment by LNQ** [comment]
Yeah, works like a charm. Thanks a lot for this fix!

**Comment by drzel** [comment]
let g:indentLine_faster = 1 breaks haml syntax highlighting.

**Comment by stsewd** [comment]
I'm using deoplete for completion, when a preview window appears neovim is very slow, if I disable indentLine or the preview window, everything is normal. Any idea why is so slow when the preview window is present?

**Comment by Yggdroot** [comment]
Now the IndentLine has been reimplemented in a new way, maybe all the issue has been fixed.
Please update it and try again. `g:indentLine_faster` is of no use now.

**Comment by alex-shamshurin** [comment]
It's not fixed! It still has totally unacceptable performance! Especially on JSX (html like) syntax. When file is opened first time - it's ok. But when I switch many times windows VIM scrolling become slower and slower each time (and finally cursor lags for 2-3 seconds). It does not happened when I switching between buffers.

**Comment by alex-shamshurin** [comment]
https://github.com/Yggdroot/indentLine/pull/224

**Comment by Seybo** [comment]
`let g:indentLine_faster = 1` doesn't make any difference for me
i have 500 lines file which is lagging a lot on scroll in the places like this
![image](https://user-images.githubusercontent.com/10584167/92439290-24b7cd00-f1c8-11ea-91d1-bf837e786caa.png)
